### ISSUE TITLE
RSS部分

### ISSUE THREAD

**Issue by skyqin1999** [AlanDecode/Maverick#16]
**Problem description**
···
Start _build_feed...Traceback (most recent call last):
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\build.py", line 43, in <module>
    main(sys.argv[1:])
    builder.build_all()
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\Maverick\Builder.py", line 173, in build_all
    self._template.render(self._config, self._posts, self._pages)
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\Templates\Kepler\__init__.py", line 19, in render
    Kepler(conf, posts, pages)()
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\Maverick\Template.py", line 158, in __call__
    self._build_feed()
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\Maverick\Utils.py", line 42, in wrapper
    func(*args, **kwargs)
  File "c:\Users\Sky Qin\Documents\Wiki\Maverick\Maverick\Template.py", line 91, in _build_feed
    fg.rss_file(unify_joinpath(self._config.build_dir, 'feed/index.xml'))
  File "C:\Users\Sky Qin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\feedgen\feed.py", line 415, in rss_file
    feed, doc = self._create_rss(extensions=extensions)
  File "C:\Users\Sky Qin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\feedgen\feed.py", line 267, in _create_rss       
    raise ValueError('Required fields not set (%s)' % missing)
ValueError: Required fields not set (title)
···
**Environment and configuration**

* Python Version: 3.7
* pip Version: 20.0.2

配置皆为默认。

**Additional information**
在此之前，会出现无法从github使用git命令克隆主题的问题：
···
Site prefix: /
Source dir: c:\Users\Sky Qin\Documents\Wiki\Maverick/test_src/
Build dir: ./test_dist/
Start clean...done.
Loading contents...
Contents loaded.
Start setup_theme...
fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]
···
通过将主题下载在/Templates文件夹下解决

**Comment by AlanDecode** [comment]
就如你说的，可能是主题安装时出现的问题。
